User.create!(nickname:  "管理者",
  email: "admin@example.jp",
  password:  "adminpower37285",
  password_confirmation: "adminpower37285",
  family_name: "蔵方",
  first_name: "翔",
  family_name_kana: "クラカタ",
  first_name_kana: "カケル",
  birthday:"2003-08-19",
  admin: true)